export default {
  policy:'/api/policy',
  yhb1loginajax:'/gy001/public/Api2024/yhb1loginajax',

  unique:'/get/unique',
  phoneCode:'/phone/code',
  imgCode:'/img/code',
  uploadImage:'/upload/image',
  userLogin:'/user/login',
  userRegister:'user/register',
  modifyPass:'/user/modify/pass',
  userInfo:'/user/info',
  product:'/index/product',
  enterpriseVerify:'/user/enterprise/verify',
  productapply:'/user/product/apply',
  userVerify:'/user/real/name/verify',
  phoneLogin:'/user/phone/login',
  policyList:'/admin/enterprise/service/policy/all/list',
  policyThemeFeature:'/admin/policy/theme/feature/list',
  policyDetail:'/enterprise/service/policy/detail',
  servicePolicy:'/enterprise/service/policy',
}
